{
    'name': 'Hardware & Support',
    'version': '19.0.1.0.0',
    'summary': 'Simple industry demo for hardware sales and support',
    'category': 'Services',
    'author': 'Abdusalomov Shaxobiddin',
    'website': 'https://www.todoo.uz',
    'license': 'LGPL-3',
    'depends': [
        'account_followup',
        'helpdesk_repair',
        'industry_fsm_sale',
        'knowledge',
        'purchase_stock',
        'sale_crm',
        'sale_purchase',
        'website_crm',
        'website_helpdesk',
        'website_sale_comparison',
        'website_sale_stock',
    ],
    'data': [
        'data/res_config_settings.xml',
        'data/stock_picking_type.xml',
        'data/project_task_type.xml',
        'data/product_category.xml',
        'data/project_project.xml',
        'data/product_template.xml',
        'data/product_attribute.xml',
        'data/product_attribute_value.xml',
        'data/product_template_attribute_line.xml',
        'data/product_template_attribute_value.xml',
        'data/product_product.xml',
        'data/sale_order_template.xml',
        'data/sale_order_template_line.xml',
        'data/knowledge_article.xml',
        'data/knowledge_article_favorite.xml',
        'data/mail_message.xml',
        'data/website_view.xml',
        'data/website_theme_apply.xml',
        'data/helpdesk_config.xml',
        'data/knowledge_tour.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'todoo_hardware/static/src/js/my_tour.js',
        ],
    },
    'images': ['static/description/images/main.png'],
    'installable': True,
    'application': True,
}
